kind: pipeline
type: docker
name: build-deploy-appointment-service

steps:
  - name: clone-stack-repo
    image: alpine/git
    environment:
      GIT_USERNAME:
        from_secret: STACK_GIT_USER
      GIT_PASSWORD:
        from_secret: STACK_GIT_TOKEN
    commands:
      - git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/maheshgowda-dwise/Argocd.git stack-repo

  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - mvn -B -ntp -Dmaven.repo.local=/root/.m2/repository clean install -DskipTests

  - name: docker-build-push
    image: plugins/docker
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      tags:
        - "v2qa-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}"
      dockerfile: Dockerfile
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  - name: update-helm-values
    image: alpine
    environment:
      GIT_USERNAME:
        from_secret: STACK_GIT_USER
      GIT_PASSWORD:
        from_secret: STACK_GIT_TOKEN
      IMAGE_TAG: "v2qa-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}"
    commands:
      - apk add --no-cache bash git
      - cd stack-repo/LT-QA/BE-Projects/BE-Canary-Helm-Unified
      - sed -i "s|image:.*|image: maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}|" values.yaml
      - git config user.email "ci@lifetrenz.local"
      - git config user.name "Lifetrenz CI"
      - git add values.yaml
      - git commit -m "chore(appointment): bump image to ${IMAGE_TAG}" || echo "No changes to commit"
      - git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/maheshgowda-dwise/Argocd.git HEAD:main

trigger:
  event:
    - push
    - manual
