kind: pipeline
type: docker
name: appointment-service-ci
steps:
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Prepare â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  - name: prepare
    image: alpine:3.18
    environment:
      TAG_PREFIX: v2qa
    commands:
      - apk add --no-cache git bash jq
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - TIMESTAMP=$(date -u +%Y%m%d%H%M)
      - IMAGE_TAG="${TAG_PREFIX}-${TIMESTAMP}-${COMMIT_HASH}"
      - echo "COMMIT_HASH=${COMMIT_HASH}" > /drone/src/.build_env
      - echo "IMAGE_TAG=${IMAGE_TAG}" >> /drone/src/.build_env
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Maven Build â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - source /drone/src/.build_env || true
      - echo "Running Maven build..."
      - mvn clean package -DskipTests
    volumes:
      - name: m2
        path: /root/.m2
    depends_on:
      - prepare
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Docker Build & Push â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  - name: docker-build-push
    image: docker:27.1.1-cli
    privileged: true
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    commands:
      - apk add --no-cache bash coreutils
      - source /drone/src/.build_env || true
      - echo "ðŸ” Logging into Docker Hub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "ðŸ³ Building Docker image..."
      - docker build -t maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG} .
      - docker tag maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG} maheshgowdamg25/lt-be-apnt-service:latest
      - echo "ðŸš€ Pushing Docker images..."
      - docker push maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}
      - docker push maheshgowdamg25/lt-be-apnt-service:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    depends_on:
      - maven-build
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Update Helm Values â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  - name: bump-stack-values
    image: alpine/git:2.40.1
    environment:
      STACK_REPO: https://github.com/maheshgowda-dwise/Argocd.git
      STACK_BRANCH: main
      STACK_FILE: LT-QA/BE-Projects/BE-Canary-Helm-Unified/values.yaml
      VALUES_SERVICE_NAME: appointment
      SERVICE_NAME: lt-be-apnt-service
      STACK_GIT_USER: ${STACK_GIT_USER}
      STACK_GIT_TOKEN: ${STACK_GIT_TOKEN}
    commands:
      - apk add --no-cache bash coreutils
      - source /drone/src/.build_env || true
      - git clone "$STACK_REPO" /tmp/stack
      - cd /tmp/stack
      - git fetch origin "$STACK_BRANCH" --prune
      - git checkout "$STACK_BRANCH"
      - echo "Updating image in $STACK_FILE for $VALUES_SERVICE_NAME"
      - sed -i "s|maheshgowdamg25/lt-be-apnt-service:.*|maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}|g" "$STACK_FILE"
      - git config --global user.email "mahesh.g@lifetrenz.com"
      - git config --global user.name "maheshgowda-dwise"
      - git add "$STACK_FILE"
      - 'git commit -m "chore(${SERVICE_NAME}): ${VALUES_SERVICE_NAME} -> ${IMAGE_TAG}" || echo "No changes to commit"'
      - AUTH_URL=$(echo "$STACK_REPO" | sed -E "s#https://#https://${STACK_GIT_USER}:${STACK_GIT_TOKEN}@#")
      - git push "$AUTH_URL" "$STACK_BRANCH"
    depends_on:
      - docker-build-push
volumes:
  - name: m2
    temp: {}
  - name: docker_sock
    host:
      path: /var/run/docker.sock
