---
kind: pipeline
type: docker
name: build-push-update-stack

steps:
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - echo "ðŸš€ Starting Maven Build..."
      - mvn -B -ntp clean install -DskipTests
      - echo "âœ… Maven build completed successfully."

  - name: docker-build-push
    image: plugins/docker
    depends_on:
      - maven-build
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - v2qa-${DRONE_COMMIT_SHA:0:7}

  - name: update-stack-repo
    image: alpine/git
    depends_on:
      - docker-build-push
    environment:
      STACK_REPO_URL: "https://github.com/maheshgowda-dwise/Argocd.git"
      STACK_BRANCH: "main"
      STACK_FILE: "LT-QA/BE-Projects/BE-Canary-Helm-Unified/values.yaml"
      VALUES_SERVICE_NAME: "appointment"
      DOCKER_REPO: "maheshgowdamg25/lt-be-apnt-service"
    commands:
      - apk add --no-cache bash git sed coreutils
      - |
        bash -euo pipefail <<'EOF'
        IMAGE_TAG="v2qa-${DRONE_COMMIT_SHA:0:7}"
        NEW_IMAGE="${DOCKER_REPO}:${IMAGE_TAG}"

        echo "ðŸ” Cloning stack repo..."
        git clone --branch "${STACK_BRANCH}" "${STACK_REPO_URL}" stack-repo
        cd stack-repo

        echo "ðŸ–‹ï¸ Checking ${STACK_FILE} for existing image..."
        if grep -q "${IMAGE_TAG}" "${STACK_FILE}"; then
          echo "âœ… Already updated (${IMAGE_TAG}), skipping commit."
          exit 0
        fi

        echo "ðŸ–‹ï¸ Updating ${STACK_FILE} with ${NEW_IMAGE}"
        sed -i "s|image:.*|image: ${NEW_IMAGE}|g" "${STACK_FILE}"

        git config user.email "mahesh.g@lifetrenz.com"
        git config user.name "maheshgowda-dwise"
        git add "${STACK_FILE}"
        git commit -m "chore(${VALUES_SERVICE_NAME}): update image to ${IMAGE_TAG}" || echo "âš ï¸ No changes to commit"
        git push "${STACK_REPO_URL}" "${STACK_BRANCH}"
        echo "ðŸš€ Stack repo updated successfully with ${NEW_IMAGE}"
        EOF

trigger:
  branch:
    - main
  event:
    - push
    - custom
