---
kind: pipeline
type: docker
name: build-and-push

steps:
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - echo "🚀 Starting Maven Build..."
      - mvn -B -ntp clean install -DskipTests
      - echo "✅ Maven build completed successfully."

  - name: prepare-tag
    image: alpine:latest
    depends_on:
      - maven-build
    commands:
      - apk add --no-cache bash coreutils
      - SHORT_COMMIT=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - TIMESTAMP=$(date +%Y%m%d%H%M)
      - IMAGE_TAG="v2qa-${TIMESTAMP}-${SHORT_COMMIT}"
      - echo "✅ Generated image tag: ${IMAGE_TAG}"
      - echo "${IMAGE_TAG}" > /tmp/image_tag

  - name: docker-build-push
    image: plugins/docker
    depends_on:
      - prepare-tag
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
    commands:
      - echo "🔖 Reading generated tag..."
      - export IMAGE_TAG=$(cat /tmp/image_tag)
      - echo "🧱 Building Docker image with tag: ${IMAGE_TAG}"
      - docker build -t maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG} .
      - docker push maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}
      - docker tag maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG} maheshgowdamg25/lt-be-apnt-service:latest
      - docker push maheshgowdamg25/lt-be-apnt-service:latest
      - echo "✅ Docker image pushed successfully as ${IMAGE_TAG}"

trigger:
  branch:
    - main
  event:
    - push
    - custom
