---
kind: pipeline
type: docker
name: build-push-update-stack

steps:
  - name: "maven-build"
    image: "maven:3.9-eclipse-temurin-17"
    commands:
      - "echo '🚀 Starting Maven Build...'"
      - "mvn -B -ntp clean install -DskipTests"
      - "echo '✅ Maven build completed successfully.'"

  - name: "prepare-tag"
    image: "alpine:latest"
    depends_on:
      - "maven-build"
    commands:
      - "apk add --no-cache bash coreutils"
      - "SHORT_COMMIT=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)"
      - "TIMESTAMP=$(date +%Y%m%d%H%M)"
      - "IMAGE_TAG=v2qa-${TIMESTAMP}-${SHORT_COMMIT}"
      - "echo ${IMAGE_TAG} > image_tag.txt"
      - "echo '✅ Generated tag:' $(cat image_tag.txt)"

  - name: "docker-build-push"
    image: "plugins/docker"
    depends_on:
      - "prepare-tag"
    settings:
      repo: "maheshgowdamg25/lt-be-apnt-service"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: "Dockerfile"
      context: "."
      tags:
        - "latest"
        - "v2qa-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}"

  - name: "update-stack-repo"
    image: "alpine/git"
    depends_on:
      - "docker-build-push"
    environment:
      STACK_REPO_URL: "https://github.com/maheshgowda-dwise/Argocd.git"
      STACK_BRANCH: "main"
      STACK_FILE: "LT-QA/BE-Projects/BE-Canary-Helm-Unified/values.yaml"
      VALUES_SERVICE_NAME: "appointment"
      DOCKER_REPO: "maheshgowdamg25/lt-be-apnt-service"
    commands:
      - "apk add --no-cache bash git sed coreutils"
      - "IMAGE_TAG=$(cat image_tag.txt)"
      - "NEW_IMAGE=${DOCKER_REPO}:${IMAGE_TAG}"
      - "echo '🔁 Cloning stack repo (public)...'"
      - "git clone --branch ${STACK_BRANCH} ${STACK_REPO_URL} stack-repo"
      - "cd stack-repo"
      - "FILE_PATH=${STACK_FILE}"
      - "echo '🖋️ Checking if update needed in ${FILE_PATH}'"
      - "if grep -q ${IMAGE_TAG} ${FILE_PATH}; then echo '✅ Already updated with ${IMAGE_TAG}, skipping commit.'; exit 0; fi"
      - "echo '🖋️ Updating ${FILE_PATH} with ${NEW_IMAGE}'"
      - "sed -i \"s|image:.*|image: ${NEW_IMAGE}|g\" ${FILE_PATH}"
      - "git config user.email 'mahesh.g@lifetrenz.com'"
      - "git config user.name 'maheshgowda-dwise'"
      - "git add ${FILE_PATH}"
      - "git commit -m \"chore(${VALUES_SERVICE_NAME}): update image to ${IMAGE_TAG}\" || echo '⚠️ No changes to commit'"
      - "git push https://github.com/maheshgowda-dwise/Argocd.git ${STACK_BRANCH}"
      - "echo '🚀 Stack repo updated successfully with ${IMAGE_TAG}'"

trigger:
  branch:
    - "main"
  event:
    - "push"
    - "custom"
