kind: pipeline
type: docker
name: appointment-service-ci

steps:
  - name: maven-clean
    image: maven:3.9-eclipse-temurin-17
    commands:
      - mvn -B clean
    volumes:
      - name: m2_cache
        path: /root/.m2

volumes:
  - name: m2_cache
    temp: {}
