---
kind: pipeline
type: docker
name: build-test-release

steps:
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - echo "🚀 Starting Maven Build..."
      - mvn -B -ntp clean install -DskipTests
      - echo "✅ Maven build completed successfully."

  - name: docker-build-push
    image: plugins/docker
    depends_on:
      - maven-build
    environment:
      TAG_PREFIX: "v2qa"
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        # Tag format: v2qa-<timestamp>-<short_commit>
        - "v2qa-$(date +%Y%m%d%H%M)-${DRONE_COMMIT_SHA:0:7}"

  - name: update-stack-repo
    image: alpine/git
    depends_on:
      - docker-build-push
    environment:
      STACK_REPO_URL: "https://github.com/maheshgowda-dwise/Argocd.git"
      STACK_BRANCH: "main"
      STACK_FILE: "LT-QA/BE-Projects/BE-Canary-Helm-Unified/values.yaml"
      VALUES_SERVICE_NAME: "appointment"
      DOCKER_REPO: "maheshgowdamg25/lt-be-apnt-service"
      TAG_PREFIX: "v2qa"
      GIT_USER:
        from_secret: git_user
      GIT_TOKEN:
        from_secret: git_token
    commands:
      - apk add --no-cache bash git sed coreutils
      - echo "🔁 Cloning stack repo..."
      - git clone --branch ${STACK_BRANCH} https://${GIT_USER}:${GIT_TOKEN}@${STACK_REPO_URL#https://} stack-repo
      - cd stack-repo
      - SHORT_COMMIT=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - TIMESTAMP=$(date +%Y%m%d%H%M)
      - IMAGE_TAG="${TAG_PREFIX}-${TIMESTAMP}-${SHORT_COMMIT}"
      - NEW_IMAGE="${DOCKER_REPO}:${IMAGE_TAG}"
      - FILE_PATH="${STACK_FILE}"
      - echo "🖋️ Updating ${FILE_PATH} with ${NEW_IMAGE}"
      - sed -i "s|image:.*|image: ${NEW_IMAGE}|g" "${FILE_PATH}"
      - git config user.email "mahesh.g@lifetrenz.com"
      - git config user.name "maheshgowda-dwise"
      - git add "${FILE_PATH}"
      - git commit -m "chore(${VALUES_SERVICE_NAME}): update image to ${IMAGE_TAG}" || echo "⚠️ No changes"
      - git push origin ${STACK_BRANCH}
      - echo "🚀 Stack repo updated successfully with ${IMAGE_TAG}"

trigger:
  branch:
    - main
  event:
    - push
    - custom
