---
kind: pipeline
type: docker
name: build-push-update-stack

steps:
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - echo "🚀 Starting Maven Build..."
      - mvn -B -ntp clean install -DskipTests
      - echo "✅ Maven build completed successfully."

  - name: docker-build-push
    image: plugins/docker
    depends_on:
      - maven-build
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - "v2qa-${DRONE_COMMIT_SHA:0:7}"

  - name: update-argocd-repo
    image: alpine/git
    depends_on:
      - docker-build-push
    commands:
      - apk add --no-cache bash git sed coreutils
      - echo "🔁 Cloning ArgoCD repo..."
      - git clone --branch main https://github.com/maheshgowda-dwise/Argocd.git stack-repo
      - cd stack-repo/LT-QA/BE-Projects/BE-Canary-Helm-Unified
      - echo "🧩 Setting up image tag variables..."
      - export IMAGE_TAG="v2qa-${DRONE_COMMIT_SHA:0:7}"
      - export NEW_IMAGE="maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}"
      - export STACK_FILE="values.yaml"
      - echo "🖋️ Checking ${STACK_FILE} for existing image..."
      - bash -c "if grep -q \"${IMAGE_TAG}\" \"${STACK_FILE}\"; then echo '✅ Already updated (${IMAGE_TAG}), skipping commit.'; exit 0; fi"
      - echo "🖋️ Updating ${STACK_FILE} with ${NEW_IMAGE}"
      - bash -c "sed -i \"s|image:.*|image: ${NEW_IMAGE}|g\" \"${STACK_FILE}\""
      - git config user.email "mahesh.g@lifetrenz.com"
      - git config user.name "maheshgowda-dwise"
      - git add "${STACK_FILE}"
      - bash -c "git commit -m \"chore(appointment): update image to ${IMAGE_TAG}\" || echo '⚠️ No changes to commit'"
      - git push https://github.com/maheshgowda-dwise/Argocd.git main
      - echo "🚀 Stack repo updated successfully with ${NEW_IMAGE}"

trigger:
  branch:
    - main
  event:
    - push
    - custom
