kind: pipeline
type: docker
name: appointment-service-ci

steps:
  - name: prepare
    image: alpine:3.18
    environment:
      TAG_PREFIX: v2qa
    commands:
      - apk add --no-cache git bash coreutils
      - |
        bash -c "
        COMMIT_HASH=\$(git rev-parse --short HEAD)
        TIMESTAMP=\$(date -u +%Y%m%d%H%M)
        IMAGE_TAG=\"${TAG_PREFIX}-\${TIMESTAMP}-\${COMMIT_HASH}\"
        echo \"IMAGE_TAG=\${IMAGE_TAG}\" > .build_env
        echo \"Generated: \${IMAGE_TAG}\"
        "
      - cat .build_env

  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - mvn -B clean package -DskipTests
    volumes:
      - name: m2_cache
        path: /root/.m2
    depends_on:
      - prepare

  - name: docker-build-push
    image: docker:20.10.17-cli
    privileged: true
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache bash
      - set -a
      - source .build_env
      - set +a
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}" .
      - docker push "maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    depends_on:
      - maven-build

volumes:
  - name: m2_cache
    temp: {}
  - name: docker_sock
    host:
      path: /var/run/docker.sock
