kind: pipeline
type: docker
name: appointment-service-ci

steps:
  # Step 2: Prepare (create IMAGE_TAG and persist for later steps)
  - name: prepare
    image: alpine:3.18
    environment:
      TAG_PREFIX: v2qa
    commands:
      - apk add --no-cache git bash
      # short commit from current checkout
      - COMMIT_HASH="$(git rev-parse --short HEAD)"
      # timestamp similar to your bash script
      - TIMESTAMP="$(date -u +%Y%m%d%H%M)"
      - IMAGE_TAG="${TAG_PREFIX}-${TIMESTAMP}-${COMMIT_HASH}"
      - echo "IMAGE_TAG=${IMAGE_TAG}"
      # persist for following steps
      - echo "export IMAGE_TAG=${IMAGE_TAG}" > .build_env

  # Step 1 (existing): Maven build (skip tests for speed)
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - mvn -B clean package -DskipTests
    volumes:
      - name: m2_cache
        path: /root/.m2
    depends_on:
      - prepare

volumes:
  - name: m2_cache
    temp: {}
