---
kind: pipeline
type: docker
name: lt-be-apnt-service-build-release

environment:
  SERVICE_NAME: lt-be-apnt-service
  VALUES_SERVICE_NAME: appointment
  TAG_PREFIX: v2qa
  MAVEN_IMAGE: maven:3.9-eclipse-temurin-17

  # Repositories
  SOURCE_REPO_URL: https://github.com/maheshgowda-dwise/appointment-service.git
  SOURCE_BRANCH: main
  STACK_REPO_URL: https://github.com/maheshgowda-dwise/Argocd.git
  STACK_BRANCH: main
  STACK_FILE_PATH: LT-QA/BE-Projects/BE-Canary-Helm-Unified/values.yaml

  # Docker Hub Repo
  DOCKER_REPO: maheshgowdamg25/lt-be-apnt-service

steps:
  - name: clone-service
    image: alpine/git
    commands:
      - echo "🚀 Cloning service repo..."
      - git clone --branch ${SOURCE_BRANCH} ${SOURCE_REPO_URL} ${SERVICE_NAME}
      - cd ${SERVICE_NAME}
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - echo "$COMMIT_HASH" > /tmp/commit_hash

  - name: build-maven
    image: ${MAVEN_IMAGE}
    depends_on: [clone-service]
    commands:
      - cd ${SERVICE_NAME}
      - echo "⚙️ Running Maven build..."
      - mvn -B -ntp clean install -DskipTests
      - echo "✅ Maven build completed"

  - name: docker-build-push
    image: plugins/docker
    depends_on: [build-maven]
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: ${SERVICE_NAME}
      tags:
        - latest
        - ${TAG_PREFIX}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - main

  - name: update-stack-repo
    image: alpine/git
    depends_on: [docker-build-push]
    environment:
      GIT_USER:
        from_secret: git_user
      GIT_TOKEN:
        from_secret: git_token
    commands:
      - apk add --no-cache git bash sed coreutils
      - echo "🔁 Cloning stack repo..."
      - git clone --branch ${STACK_BRANCH} https://${GIT_USER}:${GIT_TOKEN}@${STACK_REPO_URL#https://} stack-repo
      - cd stack-repo

      # Generate new tag
      - COMMIT_HASH=$(cat /tmp/commit_hash)
      - IMAGE_TAG="${TAG_PREFIX}-$(date +%Y%m%d%H%M)-${COMMIT_HASH}"
      - NEW_IMAGE="${DOCKER_REPO}:${IMAGE_TAG}"
      - echo "🖊️ Updating image for '${VALUES_SERVICE_NAME}' → ${NEW_IMAGE}"

      # Update Helm values file safely (single line)
      - sed -i -E "/^[[:space:]]*-[[:space:]]name:[[:space:]]*${VALUES_SERVICE_NAME}[[:space:]]*$/,/^[[:space:]]*-[[:space:]]name:[[:space:]]*/ s|^([[:space:]]*image:[[:space:]]*).*$|\1${NEW_IMAGE}|" ${STACK_FILE_PATH}

      # Commit & push
      - git config user.email "ci@lifetrenz.local"
      - git config user.name "Lifetrenz CI"
      - git add ${STACK_FILE_PATH}
      - git commit -m "chore(${SERVICE_NAME}): ${VALUES_SERVICE_NAME} -> ${IMAGE_TAG}" || echo "⚠️ No changes to commit"
      - git push origin ${STACK_BRANCH}
      - echo "✅ Stack repo updated successfully"

trigger:
  branch:
    - main
  event:
    - push
    - custom
