---
kind: pipeline
type: docker
name: build-and-push

steps:
  - name: "maven-build"
    image: "maven:3.9-eclipse-temurin-17"
    commands:
      - "echo '🚀 Starting Maven Build...'"
      - "mvn -B -ntp clean install -DskipTests"
      - "echo '✅ Maven build completed successfully.'"

  - name: "prepare-tag"
    image: "alpine:latest"
    depends_on:
      - "maven-build"
    commands:
      - "apk add --no-cache bash coreutils"
      - "SHORT_COMMIT=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)"
      - "TIMESTAMP=$(date +%Y%m%d%H%M)"
      - "IMAGE_TAG=v2qa-${TIMESTAMP}-${SHORT_COMMIT}"
      - "echo ${IMAGE_TAG} > image_tag.txt"
      - "echo '✅ Generated tag:' $(cat image_tag.txt)"

  - name: "docker-build-push"
    image: "plugins/docker"
    depends_on:
      - "prepare-tag"
    settings:
      repo: "maheshgowdamg25/lt-be-apnt-service"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: "Dockerfile"
      context: "."
      tags:
        - "latest"
        - "v2qa-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:7}"

trigger:
  branch:
    - "main"
  event:
    - "push"
    - "custom"
