---
kind: pipeline
type: docker
name: build-test-release

steps:
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - echo "🚀 Starting Maven Build..."
      - mvn -B -ntp clean install -DskipTests
      - echo "✅ Maven build completed successfully."

  - name: docker-build-push
    image: plugins/docker
    depends_on:
      - maven-build
    environment:
      TAG_PREFIX: "v2qa"
    settings:
      repo: maheshgowdamg25/lt-be-apnt-service
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        # Tag format: v2qa-<timestamp>-<short_commit>
        - "v2qa-$(date +%Y%m%d%H%M)-${DRONE_COMMIT_SHA:0:7}"

  

trigger:
  branch:
    - main
  event:
    - push
    - custom
