---
kind: pipeline
type: docker
name: maven-build-only

steps:
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - echo "🚀 Starting Maven Build..."
      - mvn  clean install -DskipTests
      - echo "✅ Maven build completed successfully."

trigger:
  branch:
    - main
  event:
    - push
    - custom
