---
kind: pipeline
type: docker
name: build-test-release

environment:
  SERVICE_NAME: lt-be-apnt-service
  TAG_PREFIX: v2qa
  MAVEN_IMAGE: maven:3.9-eclipse-temurin-17
  
  DOCKER_HUB_REPO: maheshgowdamg25/lt-be-apnt-service
  
  STACK_REPO_URL: https://github.com/maheshgowda-dwise/Argocd.git
  STACK_BRANCH: main 
  STACK_FILE: LT-QA/BE-Projects/BE-Canary-Helm-Unified/values.yaml
  VALUES_SERVICE_NAME: appointment
  STACK_LOCAL_DIR_NAME: Argocd-Stack

  STACK_REPO_USER_VAR:
    from_secret: STACK_REPO_USER
  STACK_REPO_TOKEN_VAR:
    from_secret: STACK_REPO_TOKEN

steps:

  - name: maven-build
    image: ${MAVEN_IMAGE}
    volumes:
      - name: m2-cache
        path: /root/.m2
    commands:
      - mvn clean install -DskipTests

  - name: docker-build-push
    image: plugins/docker
    settings:
      repo: ${DOCKER_HUB_REPO}
      tags:
        - ${TAG_PREFIX}-${DRONE_DATE}-latest
        - ${TAG_PREFIX}-${DRONE_DATE}-${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      branch: main
      event: push

  - name: clone-stack-repo
    image: alpine/git
    volumes:
      - name: stack-repo
        path: /stack
    environment:
      GIT_URL: ${STACK_REPO_URL}
      GIT_USER: ${STACK_REPO_USER_VAR}
      GIT_TOKEN: ${STACK_REPO_TOKEN_VAR}
    commands:
      - |
        if [ -n "$GIT_USER" ] && [ -n "$GIT_TOKEN" ]; then
          REPO_URL_WITH_CREDS="${GIT_URL/https:\/\//https:\/\/${GIT_USER}:${GIT_TOKEN}@}"
        else
          REPO_URL_WITH_CREDS="$GIT_URL"
        fi
        git clone --branch ${STACK_BRANCH} "$REPO_URL_WITH_CREDS" /stack/${STACK_LOCAL_DIR_NAME}
    when:
      branch: main
      event: push

  - name: update-stack-repo
    image: alpine/git
    volumes:
      - name: stack-repo
        path: /stack
    environment:
      STACK_FILE_PATH: /stack/${STACK_LOCAL_DIR_NAME}/${STACK_FILE}
      NEW_IMAGE: ${DOCKER_HUB_REPO}:${TAG_PREFIX}-${DRONE_DATE}-${DRONE_COMMIT_SHA}
      SERVICE_NAME_SLUG: ${VALUES_SERVICE_NAME}
      GIT_USER: ${STACK_REPO_USER_VAR}
      GIT_TOKEN: ${STACK_REPO_TOKEN_VAR}
    commands:
      - apk add --no-cache bash sed
      - cd /stack/${STACK_LOCAL_DIR_NAME}

      - echo "New Image Tag: ${NEW_IMAGE}"

      - |
        if grep -q "${DRONE_COMMIT_SHA}" "${STACK_FILE_PATH}"; then
          echo "Up to date: Commit already present. Skipping."
          exit 0
        fi

      - |
        sed -i "s|image:.*|image: ${NEW_IMAGE}|g" "${STACK_FILE_PATH}"

      - git config user.email "ci@drone.local"
      - git config user.name "Drone CI/CD"
      - git add "${STACK_FILE}"
      - git commit -m "chore(${SERVICE_NAME}): update image to ${NEW_IMAGE}" || echo "No changes to commit"
      - |
        if [ -n "$GIT_USER" ] && [ -n "$GIT_TOKEN" ]; then
          REPO_URL_WITH_CREDS="${STACK_REPO_URL/https:\/\//https:\/\/${GIT_USER}:${GIT_TOKEN}@}"
        else
          REPO_URL_WITH_CREDS="${STACK_REPO_URL}"
        fi
        git push "${REPO_URL_WITH_CREDS}" ${STACK_BRANCH}
        echo "Values updated and pushed."
    when:
      branch: main
      event: push

volumes:
  - name: m2-cache
    host:
      path: /tmp/drone/m2_cache
  - name: stack-repo
    host:
      path: /tmp/drone/stack_repo

trigger:
  branch:
    - main
  event:
    - push
