kind: pipeline
type: docker
name: appointment-service-ci

steps:
  # Step 1: Maven Build
  - name: maven-build
    image: maven:3.9-eclipse-temurin-17
    commands:
      - mvn -B clean package -DskipTests
    volumes:
      - name: m2_cache
        path: /root/.m2

  # Step 2: Docker Build & Push with dynamic IMAGE_TAG
  - name: docker-build-push
    image: docker:20.10.17-cli
    privileged: true
    environment:
      TAG_PREFIX: v2qa
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache bash git coreutils
      - |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        TIMESTAMP=$(date -u +%Y%m%d%H%M)
        IMAGE_TAG="${TAG_PREFIX}-${TIMESTAMP}-${COMMIT_HASH}"
        echo "Using tag: ${IMAGE_TAG}"
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t "maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}" .
        docker push "maheshgowdamg25/lt-be-apnt-service:${IMAGE_TAG}"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    depends_on:
      - maven-build

volumes:
  - name: m2_cache
    temp: {}
  - name: docker_sock
    host:
      path: /var/run/docker.sock
