package com.lifetrenz.lths.appointment.enums;

/**
 *
 * @author Sai.KVSS
 *
 */
public enum ClinicalEventType {

	ADD_ADMISSION_DASHBOARD("ADD-ADMISSION-DASHBOARD"), TRIAGE("TRIAGE"), CASETYPE("CASETYPE"),
	DIET_ADVICE_REQUEST("DIET_ADVICE_REQUEST"), DIET_ADVICE_ASSESSMENT("DIET_ADVICE_ASSESSMENT"),
	PATIENT_ALLERGY("PATIENT_ALLERGY"), PATIENT_DIAGNOSIS("PATIENT_DIAGNOSIS"), ANAESTHESIA("ANAESTHESIA"),
	DELIVERY_TYPE("DELIVERY_TYPE"), OT_ORDER_STATUS("OT_ORDER_STATUS"),
	PATIENT_REFERRAL_CONSULTATION("PATIENT_REFERRAL_CONSULTATION"), DISCHARE_INITIATE("DISCHARE_INITIATE"),
	PATIENT_ALLERGY_DELETE("PATIENT_ALLERGY_DELETE"), DIAGNOSIS_DELETE("DIAGNOSIS_DELETE"),
	CONDUCT_STATUS("CONDUCT_STATUS"), IP_OT_ORDER("IP-OT-ORDER"), IP_OT_ORDER_SCHEDULE("IP-OT-ORDER-SCHEDULE"),
	ADD_IP_CCS_ADMISSION_DASHBOARD("ADD_IP_CCS_ADMISSION_DASHBOARD"),
	ADD_IP_ADMISSION_DASHBOARD("ADD_IP_ADMISSION_DASHBOARD"),
	UPDATE_PATIENT_VISIT_NOTE_INSTRUMENTS("UPDATE_PATIENT_VISIT_NOTE_INSTRUMENTS"),
	OP_ADMIT_REQUEST("OP_ADMIT_REQUEST"), ER_ADMIT_REQUEST("ER_ADMIT_REQUEST"),
	UPDATE_REFERRAL_CONSULTATION_STATUS("UPDATE_REFERRAL_CONSULTATION_STATUS"),
	DELETE_REFERRAL_CONSULTATION("DELETE_REFERRAL_CONSULTATION"),DISCHARGE_PLANING("DISCHARGE_PLANING"),
	DISCHARGE_COMPLETED("DISCHARGE_COMPLETED"),NEW_BIRTH("NEW_BIRTH"), UPDATE_REF_APT_BOOK_STATUS("UPDATE_REF_APT_BOOK_STATUS");

	public final String value;

	/**
	 * @param string
	 */
	ClinicalEventType(String string) {
		value = string;
	}

}
