package com.lifetrenz.lths.appointment.enums;

/**
 * 
 * @author Nagendra.K
 *
 */
public enum FilterComponentType {

	ALLAPP("ALLAPP"), NEWREG("NEWREG"), ACCSTMTS("ACCSTMTS"), IPNEWADM("IPNEWADM"), IPOPNBLS("IPOPNBLS"),
	IPDNFB("IPDNFB"), FINBILL("FINBILL"), IPPENDSETLMT("IPPENDSETLMT"), ADM_RPT("ADM_RPT"), INVCRPT("INVCRPT"),
	COLLCTNRPT("COLLCTNRPT"), ITMGRPRPT("ITMGRPRPT"), DISCHRG_RPT("DISCHRG_RPT"), UNB_ADM_RPT("UNB_ADM_RPT"),
	TXRPRT("TXRPRT"), DCNTRPRT("DCNTRPRT"), IPUNBLITGRP("IPUNBLITGRP"), CNCLINVCS("CNCLINVCS"), CRDTNOTE("CRDTNOTE"),
	REFADV("REFADV"), CNCLINVREQ("CNCLINVREQ"), IPNEWADMORD("IPNEWADMORD"), FDMBOOK("FDMBOOK"), BLOPAT("BLOPAT"),
	BLOPATQ("BLOPATQ"), BLOSLT("BLOSLT"), NONAVA("NONAVA"), ADSCH("ADSCH"), PENRES("PENRES");

	public final String value;

	/**
	 * @param i
	 */
	FilterComponentType(String i) {
		value = i;
	}

}