package com.lifetrenz.lths.appointment.model.enums;

public enum RelayEventType {
     ADD_HATI_APPOINTMENT("ADD_HATI_APPOINTMENT"),
	ADD_CLINICAL_APPOINTMENT("ADD_CLINICAL_APPOINTMENT"), APPOINTMENT_CANCEL_TOPIC("APPOINTMENT_CANCEL_TOPIC"),
	APPOINTMENT_CLINICAL_RESCHEDULE_APPOINTMENT("APPOINTMENT_CLINICAL_RESCHEDULE_APPOINTMENT"),
	RELAY_RESCHEDULE_APPOINTMENT("RELAY_RESCHEDULE_APPOINTMENT"),
	APPOINTMENT_CLINICAL_CANCEL_TOPIC("APPOINTMENT_CLINICAL_CANCEL_TOPIC");

	public final String value;

	/**
	 * @param string
	 */
	RelayEventType(String string) {
		value = string;
	}

}
